# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\CEID\Βασεις Δεδομενων\ProjectDB\Admin.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AdminWindow(object):
    def setupUi(self, AdminWindow):
        AdminWindow.setObjectName("AdminWindow")
        AdminWindow.resize(650, 350)
        AdminWindow.setMinimumSize(QtCore.QSize(650, 350))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        AdminWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(AdminWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setObjectName("Save")
        self.gridLayout.addWidget(self.Save, 2, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset.sizePolicy().hasHeightForWidth())
        self.Reset.setSizePolicy(sizePolicy)
        self.Reset.setObjectName("Reset")
        self.gridLayout.addWidget(self.Reset, 2, 3, 1, 1)
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 2, 0, 1, 1)
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setBold(False)
        font.setWeight(50)
        self.Tabs.setFont(font)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tabs.setIconSize(QtCore.QSize(16, 16))
        self.Tabs.setElideMode(QtCore.Qt.ElideNone)
        self.Tabs.setUsesScrollButtons(False)
        self.Tabs.setDocumentMode(False)
        self.Tabs.setTabsClosable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.ACCOUNT = QtWidgets.QWidget()
        self.ACCOUNT.setObjectName("ACCOUNT")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.ACCOUNT)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self._username = QtWidgets.QLabel(self.ACCOUNT)
        self._username.setObjectName("_username")
        self.gridLayout_5.addWidget(self._username, 0, 0, 1, 1)
        self.Username = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Username.setEnabled(True)
        self.Username.setReadOnly(True)
        self.Username.setObjectName("Username")
        self.gridLayout_5.addWidget(self.Username, 0, 1, 1, 1)
        self._password = QtWidgets.QLabel(self.ACCOUNT)
        self._password.setObjectName("_password")
        self.gridLayout_5.addWidget(self._password, 0, 2, 1, 1)
        self.Password = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.Password.setObjectName("Password")
        self.gridLayout_5.addWidget(self.Password, 0, 3, 1, 1)
        self._name = QtWidgets.QLabel(self.ACCOUNT)
        self._name.setObjectName("_name")
        self.gridLayout_5.addWidget(self._name, 1, 0, 1, 1)
        self.Name = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Name.setObjectName("Name")
        self.gridLayout_5.addWidget(self.Name, 1, 1, 1, 1)
        self._surname = QtWidgets.QLabel(self.ACCOUNT)
        self._surname.setObjectName("_surname")
        self.gridLayout_5.addWidget(self._surname, 1, 2, 1, 1)
        self.Surname = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Surname.setObjectName("Surname")
        self.gridLayout_5.addWidget(self.Surname, 1, 3, 1, 1)
        self._regdate = QtWidgets.QLabel(self.ACCOUNT)
        self._regdate.setObjectName("_regdate")
        self.gridLayout_5.addWidget(self._regdate, 2, 0, 1, 1)
        self.Regdate = QtWidgets.QDateTimeEdit(self.ACCOUNT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Regdate.sizePolicy().hasHeightForWidth())
        self.Regdate.setSizePolicy(sizePolicy)
        self.Regdate.setReadOnly(True)
        self.Regdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.Regdate.setProperty("showGroupSeparator", False)
        self.Regdate.setDisplayFormat("dd-MM-yyyy HH:mm:ss")
        self.Regdate.setObjectName("Regdate")
        self.gridLayout_5.addWidget(self.Regdate, 2, 1, 1, 1)
        self._email = QtWidgets.QLabel(self.ACCOUNT)
        self._email.setObjectName("_email")
        self.gridLayout_5.addWidget(self._email, 2, 2, 1, 1)
        self.Email = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Email.setObjectName("Email")
        self.gridLayout_5.addWidget(self.Email, 2, 3, 1, 1)
        self.stackedRC = QtWidgets.QStackedWidget(self.ACCOUNT)
        self.stackedRC.setObjectName("stackedRC")
        self.blank = QtWidgets.QWidget()
        self.blank.setObjectName("blank")
        self.stackedRC.addWidget(self.blank)
        self.stack_recruiter = QtWidgets.QWidget()
        self.stack_recruiter.setObjectName("stack_recruiter")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.stack_recruiter)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.R_expyears = QtWidgets.QLabel(self.stack_recruiter)
        self.R_expyears.setObjectName("R_expyears")
        self.gridLayout_2.addWidget(self.R_expyears, 0, 0, 1, 1)
        self.RExpYears = QtWidgets.QSpinBox(self.stack_recruiter)
        self.RExpYears.setObjectName("RExpYears")
        self.gridLayout_2.addWidget(self.RExpYears, 0, 1, 1, 1)
        self.Rfirm = QtWidgets.QLabel(self.stack_recruiter)
        self.Rfirm.setObjectName("Rfirm")
        self.gridLayout_2.addWidget(self.Rfirm, 0, 2, 1, 1)
        self.RFirm = QtWidgets.QComboBox(self.stack_recruiter)
        self.RFirm.setObjectName("RFirm")
        self.gridLayout_2.addWidget(self.RFirm, 0, 3, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 108, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 2, 1, 1)
        self.stackedRC.addWidget(self.stack_recruiter)
        self.stack_candidate = QtWidgets.QWidget()
        self.stack_candidate.setObjectName("stack_candidate")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.stack_candidate)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.CCertificates = QtWidgets.QLineEdit(self.stack_candidate)
        self.CCertificates.setObjectName("CCertificates")
        self.gridLayout_6.addWidget(self.CCertificates, 0, 3, 1, 1)
        self.C_biography = QtWidgets.QLabel(self.stack_candidate)
        self.C_biography.setObjectName("C_biography")
        self.gridLayout_6.addWidget(self.C_biography, 1, 0, 1, 1)
        self.CRecommendations = QtWidgets.QLineEdit(self.stack_candidate)
        self.CRecommendations.setObjectName("CRecommendations")
        self.gridLayout_6.addWidget(self.CRecommendations, 0, 1, 1, 1)
        self.C_certificates = QtWidgets.QLabel(self.stack_candidate)
        self.C_certificates.setObjectName("C_certificates")
        self.gridLayout_6.addWidget(self.C_certificates, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 2, 0, 1, 1)
        self.CBiography = QtWidgets.QPlainTextEdit(self.stack_candidate)
        self.CBiography.setObjectName("CBiography")
        self.gridLayout_6.addWidget(self.CBiography, 1, 1, 2, 3)
        self.C_recommendations = QtWidgets.QLabel(self.stack_candidate)
        self.C_recommendations.setObjectName("C_recommendations")
        self.gridLayout_6.addWidget(self.C_recommendations, 0, 0, 1, 1)
        self.stackedRC.addWidget(self.stack_candidate)
        self.gridLayout_5.addWidget(self.stackedRC, 4, 0, 1, 4)
        self.RCChoose = QtWidgets.QComboBox(self.ACCOUNT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RCChoose.sizePolicy().hasHeightForWidth())
        self.RCChoose.setSizePolicy(sizePolicy)
        self.RCChoose.setObjectName("RCChoose")
        self.RCChoose.addItem("")
        self.RCChoose.addItem("")
        self.gridLayout_5.addWidget(self.RCChoose, 3, 1, 1, 1)
        self.RC_choose = QtWidgets.QLabel(self.ACCOUNT)
        self.RC_choose.setObjectName("RC_choose")
        self.gridLayout_5.addWidget(self.RC_choose, 3, 0, 1, 1)
        self.Tabs.addTab(self.ACCOUNT, "")
        self.WORKPOS = QtWidgets.QWidget()
        self.WORKPOS.setObjectName("WORKPOS")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.WORKPOS)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.FS_choose = QtWidgets.QLabel(self.WORKPOS)
        self.FS_choose.setObjectName("FS_choose")
        self.gridLayout_3.addWidget(self.FS_choose, 0, 0, 1, 2)
        self.FSCHoose = QtWidgets.QComboBox(self.WORKPOS)
        self.FSCHoose.setObjectName("FSCHoose")
        self.FSCHoose.addItem("")
        self.FSCHoose.addItem("")
        self.gridLayout_3.addWidget(self.FSCHoose, 0, 2, 1, 1)
        self.FS_title = QtWidgets.QLabel(self.WORKPOS)
        self.FS_title.setObjectName("FS_title")
        self.gridLayout_3.addWidget(self.FS_title, 1, 0, 1, 1)
        self.FSTitle = QtWidgets.QLineEdit(self.WORKPOS)
        self.FSTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.FSTitle.setObjectName("FSTitle")
        self.gridLayout_3.addWidget(self.FSTitle, 1, 1, 1, 2)
        self.FS_belongs = QtWidgets.QLabel(self.WORKPOS)
        self.FS_belongs.setObjectName("FS_belongs")
        self.gridLayout_3.addWidget(self.FS_belongs, 1, 3, 1, 1)
        self.FSBelongs = QtWidgets.QComboBox(self.WORKPOS)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.FSBelongs.sizePolicy().hasHeightForWidth())
        self.FSBelongs.setSizePolicy(sizePolicy)
        self.FSBelongs.setObjectName("FSBelongs")
        self.gridLayout_3.addWidget(self.FSBelongs, 1, 4, 1, 1)
        self.FS_rootcheck = QtWidgets.QCheckBox(self.WORKPOS)
        self.FS_rootcheck.setObjectName("FS_rootcheck")
        self.gridLayout_3.addWidget(self.FS_rootcheck, 2, 4, 1, 1)
        self.FS_description = QtWidgets.QLabel(self.WORKPOS)
        self.FS_description.setObjectName("FS_description")
        self.gridLayout_3.addWidget(self.FS_description, 3, 0, 1, 1)
        self.FSDecription = QtWidgets.QTextEdit(self.WORKPOS)
        self.FSDecription.setObjectName("FSDecription")
        self.gridLayout_3.addWidget(self.FSDecription, 3, 1, 3, 4)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem3, 4, 0, 1, 1)
        self.Tabs.addTab(self.WORKPOS, "")
        self.HISTORY = QtWidgets.QWidget()
        self.HISTORY.setObjectName("HISTORY")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.HISTORY)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.HResults = QtWidgets.QTableWidget(self.HISTORY)
        self.HResults.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.HResults.setAlternatingRowColors(True)
        self.HResults.setObjectName("HResults")
        self.HResults.setColumnCount(5)
        self.HResults.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.HResults.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.HResults.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.HResults.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.HResults.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.HResults.setHorizontalHeaderItem(4, item)
        self.gridLayout_4.addWidget(self.HResults, 2, 0, 1, 3)
        self.HOrder2 = QtWidgets.QComboBox(self.HISTORY)
        self.HOrder2.setObjectName("HOrder2")
        self.gridLayout_4.addWidget(self.HOrder2, 0, 2, 1, 1)
        self.H_order = QtWidgets.QLabel(self.HISTORY)
        self.H_order.setObjectName("H_order")
        self.gridLayout_4.addWidget(self.H_order, 0, 0, 1, 1)
        self.HOrder = QtWidgets.QComboBox(self.HISTORY)
        self.HOrder.setCurrentText("")
        self.HOrder.setInsertPolicy(QtWidgets.QComboBox.NoInsert)
        self.HOrder.setObjectName("HOrder")
        self.HOrder.addItem("")
        self.HOrder.addItem("")
        self.gridLayout_4.addWidget(self.HOrder, 0, 1, 1, 1)
        self.H_timeperiod = QtWidgets.QLabel(self.HISTORY)
        self.H_timeperiod.setObjectName("H_timeperiod")
        self.gridLayout_4.addWidget(self.H_timeperiod, 1, 0, 1, 1)
        self.HTPStart = QtWidgets.QDateEdit(self.HISTORY)
        self.HTPStart.setObjectName("HTPStart")
        self.gridLayout_4.addWidget(self.HTPStart, 1, 1, 1, 1)
        self.HTPEnd = QtWidgets.QDateEdit(self.HISTORY)
        self.HTPEnd.setObjectName("HTPEnd")
        self.gridLayout_4.addWidget(self.HTPEnd, 1, 2, 1, 1)
        self.Tabs.addTab(self.HISTORY, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 4)
        AdminWindow.setCentralWidget(self.centralwidget)
        self._username.setBuddy(self.Username)
        self._password.setBuddy(self.Password)
        self._name.setBuddy(self.Name)
        self._surname.setBuddy(self.Surname)
        self._regdate.setBuddy(self.Regdate)
        self._email.setBuddy(self.Email)
        self.C_biography.setBuddy(self.CBiography)
        self.C_certificates.setBuddy(self.CCertificates)
        self.C_recommendations.setBuddy(self.CRecommendations)
        self.FS_title.setBuddy(self.FSTitle)

        self.retranslateUi(AdminWindow)
        self.Tabs.setCurrentIndex(1)
        self.stackedRC.setCurrentIndex(2)
        self.FSCHoose.setCurrentIndex(-1)
        self.HOrder.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(AdminWindow)
        AdminWindow.setTabOrder(self.Tabs, self.Username)
        AdminWindow.setTabOrder(self.Username, self.Password)
        AdminWindow.setTabOrder(self.Password, self.Name)
        AdminWindow.setTabOrder(self.Name, self.Surname)
        AdminWindow.setTabOrder(self.Surname, self.Regdate)
        AdminWindow.setTabOrder(self.Regdate, self.Email)
        AdminWindow.setTabOrder(self.Email, self.RCChoose)
        AdminWindow.setTabOrder(self.RCChoose, self.RExpYears)
        AdminWindow.setTabOrder(self.RExpYears, self.RFirm)
        AdminWindow.setTabOrder(self.RFirm, self.CRecommendations)
        AdminWindow.setTabOrder(self.CRecommendations, self.CCertificates)
        AdminWindow.setTabOrder(self.CCertificates, self.CBiography)
        AdminWindow.setTabOrder(self.CBiography, self.FSCHoose)
        AdminWindow.setTabOrder(self.FSCHoose, self.FSTitle)
        AdminWindow.setTabOrder(self.FSTitle, self.FSBelongs)
        AdminWindow.setTabOrder(self.FSBelongs, self.FS_rootcheck)
        AdminWindow.setTabOrder(self.FS_rootcheck, self.FSDecription)
        AdminWindow.setTabOrder(self.FSDecription, self.HOrder)
        AdminWindow.setTabOrder(self.HOrder, self.HOrder2)
        AdminWindow.setTabOrder(self.HOrder2, self.HResults)
        AdminWindow.setTabOrder(self.HResults, self.Reset)
        AdminWindow.setTabOrder(self.Reset, self.Save)
        AdminWindow.setTabOrder(self.Save, self.Exit)
        AdminWindow.setTabOrder(self.Exit, AdminWindow.Regdate_3)
        AdminWindow.setTabOrder(AdminWindow.Regdate_3, AdminWindow.Email_3)
        AdminWindow.setTabOrder(AdminWindow.Email_3, AdminWindow.lineEdit_5)
        AdminWindow.setTabOrder(AdminWindow.lineEdit_5, AdminWindow.lineEdit_6)
        AdminWindow.setTabOrder(AdminWindow.lineEdit_6, AdminWindow.plainTextEdit_3)
        AdminWindow.setTabOrder(AdminWindow.plainTextEdit_3, AdminWindow.spinBox_3)
        AdminWindow.setTabOrder(AdminWindow.spinBox_3, AdminWindow.comboBox_7)
        AdminWindow.setTabOrder(AdminWindow.comboBox_7, AdminWindow.comboBox_8)
        AdminWindow.setTabOrder(AdminWindow.comboBox_8, AdminWindow.comboBox_9)
        AdminWindow.setTabOrder(AdminWindow.comboBox_9, AdminWindow.textEdit_3)
        AdminWindow.setTabOrder(AdminWindow.textEdit_3, AdminWindow.JTitle_3)
        AdminWindow.setTabOrder(AdminWindow.JTitle_3, AdminWindow.checkBox_3)
        AdminWindow.setTabOrder(AdminWindow.checkBox_3, AdminWindow.Password_3)
        AdminWindow.setTabOrder(AdminWindow.Password_3, AdminWindow.Surname_3)
        AdminWindow.setTabOrder(AdminWindow.Surname_3, AdminWindow.Name_3)
        AdminWindow.setTabOrder(AdminWindow.Name_3, AdminWindow.Username_3)

    def retranslateUi(self, AdminWindow):
        _translate = QtCore.QCoreApplication.translate
        AdminWindow.setWindowTitle(_translate("AdminWindow", "MainWindow"))
        self.Save.setText(_translate("AdminWindow", "Add"))
        self.Reset.setText(_translate("AdminWindow", "Clear"))
        self.Exit.setText(_translate("AdminWindow", "Log out"))
        self._username.setText(_translate("AdminWindow", "Username"))
        self._password.setText(_translate("AdminWindow", "Password"))
        self._name.setText(_translate("AdminWindow", "Name"))
        self._surname.setText(_translate("AdminWindow", "Surname"))
        self._regdate.setText(_translate("AdminWindow", "Register date"))
        self._email.setText(_translate("AdminWindow", "E-Mail"))
        self.R_expyears.setText(_translate("AdminWindow", "Years of Experience"))
        self.Rfirm.setText(_translate("AdminWindow", "Firm"))
        self.C_biography.setText(_translate("AdminWindow", "Biography"))
        self.C_certificates.setText(_translate("AdminWindow", "Certificates"))
        self.C_recommendations.setText(_translate("AdminWindow", "Reccomendations"))
        self.RCChoose.setItemText(0, _translate("AdminWindow", "Recruiter"))
        self.RCChoose.setItemText(1, _translate("AdminWindow", "Candidate"))
        self.RC_choose.setText(_translate("AdminWindow", "Choose type of user:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ACCOUNT), _translate("AdminWindow", "Add an Account"))
        self.FS_choose.setText(_translate("AdminWindow", "Choose what to add:"))
        self.FSCHoose.setItemText(0, _translate("AdminWindow", "Field"))
        self.FSCHoose.setItemText(1, _translate("AdminWindow", "Subject"))
        self.FS_title.setText(_translate("AdminWindow", "Title"))
        self.FS_belongs.setText(_translate("AdminWindow", "Belongs to:"))
        self.FS_rootcheck.setText(_translate("AdminWindow", "Root Element"))
        self.FS_description.setText(_translate("AdminWindow", "Description"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.WORKPOS), _translate("AdminWindow", "Add a Field or Subject"))
        item = self.HResults.horizontalHeaderItem(0)
        item.setText(_translate("AdminWindow", "User"))
        item = self.HResults.horizontalHeaderItem(1)
        item.setText(_translate("AdminWindow", "Date"))
        item = self.HResults.horizontalHeaderItem(2)
        item.setText(_translate("AdminWindow", "Status"))
        item = self.HResults.horizontalHeaderItem(3)
        item.setText(_translate("AdminWindow", "Type"))
        item = self.HResults.horizontalHeaderItem(4)
        item.setText(_translate("AdminWindow", "Table Name"))
        self.H_order.setText(_translate("AdminWindow", "Order By:"))
        self.HOrder.setItemText(0, _translate("AdminWindow", "Table"))
        self.HOrder.setItemText(1, _translate("AdminWindow", "User"))
        self.H_timeperiod.setText(_translate("AdminWindow", "Time period"))
        self.HTPStart.setDisplayFormat(_translate("AdminWindow", "dd-MM-yyyy"))
        self.HTPEnd.setDisplayFormat(_translate("AdminWindow", "dd-MM-yyyy"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.HISTORY), _translate("AdminWindow", "History"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AdminWindow = QtWidgets.QMainWindow()
    ui = Ui_AdminWindow()
    ui.setupUi(AdminWindow)
    AdminWindow.show()
    sys.exit(app.exec_())

