# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Documents\CEID\Βασεις Δεδομενων\ProjectDB\Candidate.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_CandidateWindow(object):
    def setupUi(self, CandidateWindow):
        CandidateWindow.setObjectName("CandidateWindow")
        CandidateWindow.resize(650, 350)
        CandidateWindow.setMinimumSize(QtCore.QSize(650, 350))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        CandidateWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(CandidateWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 1)
        self.Exit = QtWidgets.QPushButton(self.centralwidget)
        self.Exit.setObjectName("Exit")
        self.gridLayout.addWidget(self.Exit, 2, 0, 1, 1)
        self.Reset = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Reset.sizePolicy().hasHeightForWidth())
        self.Reset.setSizePolicy(sizePolicy)
        self.Reset.setObjectName("Reset")
        self.gridLayout.addWidget(self.Reset, 2, 3, 1, 1)
        self.Save = QtWidgets.QPushButton(self.centralwidget)
        self.Save.setObjectName("Save")
        self.gridLayout.addWidget(self.Save, 2, 2, 1, 1)
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tabs.sizePolicy().hasHeightForWidth())
        self.Tabs.setSizePolicy(sizePolicy)
        self.Tabs.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Bahnschrift Light")
        font.setBold(False)
        font.setWeight(50)
        self.Tabs.setFont(font)
        self.Tabs.setTabPosition(QtWidgets.QTabWidget.North)
        self.Tabs.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.Tabs.setIconSize(QtCore.QSize(16, 16))
        self.Tabs.setElideMode(QtCore.Qt.ElideNone)
        self.Tabs.setUsesScrollButtons(False)
        self.Tabs.setDocumentMode(False)
        self.Tabs.setTabsClosable(False)
        self.Tabs.setTabBarAutoHide(False)
        self.Tabs.setObjectName("Tabs")
        self.ACCOUNT = QtWidgets.QWidget()
        self.ACCOUNT.setObjectName("ACCOUNT")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.ACCOUNT)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self._username = QtWidgets.QLabel(self.ACCOUNT)
        self._username.setObjectName("_username")
        self.gridLayout_2.addWidget(self._username, 0, 0, 1, 1)
        self.Username = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Username.setEnabled(True)
        self.Username.setReadOnly(True)
        self.Username.setObjectName("Username")
        self.gridLayout_2.addWidget(self.Username, 0, 1, 1, 1)
        self._password = QtWidgets.QLabel(self.ACCOUNT)
        self._password.setObjectName("_password")
        self.gridLayout_2.addWidget(self._password, 0, 2, 1, 1)
        self.Password = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.Password.setObjectName("Password")
        self.gridLayout_2.addWidget(self.Password, 0, 3, 1, 1)
        self._name = QtWidgets.QLabel(self.ACCOUNT)
        self._name.setObjectName("_name")
        self.gridLayout_2.addWidget(self._name, 1, 0, 1, 1)
        self.Name = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Name.setObjectName("Name")
        self.gridLayout_2.addWidget(self.Name, 1, 1, 1, 1)
        self._surname = QtWidgets.QLabel(self.ACCOUNT)
        self._surname.setObjectName("_surname")
        self.gridLayout_2.addWidget(self._surname, 1, 2, 1, 1)
        self.Surname = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Surname.setObjectName("Surname")
        self.gridLayout_2.addWidget(self.Surname, 1, 3, 1, 1)
        self._regdate = QtWidgets.QLabel(self.ACCOUNT)
        self._regdate.setObjectName("_regdate")
        self.gridLayout_2.addWidget(self._regdate, 2, 0, 1, 1)
        self.Regdate = QtWidgets.QDateTimeEdit(self.ACCOUNT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Regdate.sizePolicy().hasHeightForWidth())
        self.Regdate.setSizePolicy(sizePolicy)
        self.Regdate.setFrame(True)
        self.Regdate.setReadOnly(False)
        self.Regdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.Regdate.setProperty("showGroupSeparator", False)
        self.Regdate.setDisplayFormat("dd-MM-yyyy HH:mm:ss")
        self.Regdate.setObjectName("Regdate")
        self.gridLayout_2.addWidget(self.Regdate, 2, 1, 1, 1)
        self._email = QtWidgets.QLabel(self.ACCOUNT)
        self._email.setObjectName("_email")
        self.gridLayout_2.addWidget(self._email, 2, 2, 1, 1)
        self.Email = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Email.setObjectName("Email")
        self.gridLayout_2.addWidget(self.Email, 2, 3, 1, 1)
        self._recommendations = QtWidgets.QLabel(self.ACCOUNT)
        self._recommendations.setObjectName("_recommendations")
        self.gridLayout_2.addWidget(self._recommendations, 3, 0, 1, 1)
        self.Recommendations = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Recommendations.setObjectName("Recommendations")
        self.gridLayout_2.addWidget(self.Recommendations, 3, 1, 1, 1)
        self._certificates = QtWidgets.QLabel(self.ACCOUNT)
        self._certificates.setObjectName("_certificates")
        self.gridLayout_2.addWidget(self._certificates, 3, 2, 1, 1)
        self.Certificates = QtWidgets.QLineEdit(self.ACCOUNT)
        self.Certificates.setObjectName("Certificates")
        self.gridLayout_2.addWidget(self.Certificates, 3, 3, 1, 1)
        self.C_biography = QtWidgets.QLabel(self.ACCOUNT)
        self.C_biography.setObjectName("C_biography")
        self.gridLayout_2.addWidget(self.C_biography, 4, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 5, 0, 1, 1)
        self.CBiography = QtWidgets.QPlainTextEdit(self.ACCOUNT)
        self.CBiography.setReadOnly(True)
        self.CBiography.setObjectName("CBiography")
        self.gridLayout_2.addWidget(self.CBiography, 4, 1, 2, 3)
        self.Tabs.addTab(self.ACCOUNT, "")
        self.APPLIC = QtWidgets.QWidget()
        self.APPLIC.setObjectName("APPLIC")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.APPLIC)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.C_idpos = QtWidgets.QLabel(self.APPLIC)
        self.C_idpos.setObjectName("C_idpos")
        self.gridLayout_3.addWidget(self.C_idpos, 0, 0, 1, 2)
        self.CTitle = QtWidgets.QLineEdit(self.APPLIC)
        self.CTitle.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CTitle.setReadOnly(True)
        self.CTitle.setObjectName("CTitle")
        self.gridLayout_3.addWidget(self.CTitle, 1, 1, 1, 1)
        self.C_recruiter = QtWidgets.QLabel(self.APPLIC)
        self.C_recruiter.setObjectName("C_recruiter")
        self.gridLayout_3.addWidget(self.C_recruiter, 1, 2, 1, 1)
        self.C_position = QtWidgets.QLabel(self.APPLIC)
        self.C_position.setObjectName("C_position")
        self.gridLayout_3.addWidget(self.C_position, 1, 0, 1, 1)
        self.CRecruiter = QtWidgets.QLineEdit(self.APPLIC)
        self.CRecruiter.setReadOnly(True)
        self.CRecruiter.setObjectName("CRecruiter")
        self.gridLayout_3.addWidget(self.CRecruiter, 1, 3, 1, 1)
        self.C_edra = QtWidgets.QLabel(self.APPLIC)
        self.C_edra.setObjectName("C_edra")
        self.gridLayout_3.addWidget(self.C_edra, 2, 0, 1, 1)
        self.C_subdate = QtWidgets.QLabel(self.APPLIC)
        self.C_subdate.setObjectName("C_subdate")
        self.gridLayout_3.addWidget(self.C_subdate, 3, 2, 1, 1)
        self.CEdra = QtWidgets.QLineEdit(self.APPLIC)
        self.CEdra.setReadOnly(True)
        self.CEdra.setObjectName("CEdra")
        self.gridLayout_3.addWidget(self.CEdra, 2, 1, 1, 1)
        self.C_salary = QtWidgets.QLabel(self.APPLIC)
        self.C_salary.setObjectName("C_salary")
        self.gridLayout_3.addWidget(self.C_salary, 3, 0, 1, 1)
        self.CStartdate = QtWidgets.QDateEdit(self.APPLIC)
        self.CStartdate.setReadOnly(True)
        self.CStartdate.setDisplayFormat("dd-MM-yyyy")
        self.CStartdate.setObjectName("CStartdate")
        self.gridLayout_3.addWidget(self.CStartdate, 2, 3, 1, 1)
        self.C_startdate = QtWidgets.QLabel(self.APPLIC)
        self.C_startdate.setObjectName("C_startdate")
        self.gridLayout_3.addWidget(self.C_startdate, 2, 2, 1, 1)
        self.CAppFile = QtWidgets.QLineEdit(self.APPLIC)
        self.CAppFile.setObjectName("CAppFile")
        self.gridLayout_3.addWidget(self.CAppFile, 4, 1, 1, 1)
        self.CSubdate = QtWidgets.QDateEdit(self.APPLIC)
        self.CSubdate.setReadOnly(True)
        self.CSubdate.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.CSubdate.setDisplayFormat("dd-MM-yyyy")
        self.CSubdate.setObjectName("CSubdate")
        self.gridLayout_3.addWidget(self.CSubdate, 3, 3, 1, 1)
        self.C_appfile = QtWidgets.QLabel(self.APPLIC)
        self.C_appfile.setObjectName("C_appfile")
        self.gridLayout_3.addWidget(self.C_appfile, 4, 0, 1, 1)
        self.CSalary = QtWidgets.QSpinBox(self.APPLIC)
        self.CSalary.setReadOnly(True)
        self.CSalary.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.CSalary.setMaximum(1000000000)
        self.CSalary.setObjectName("CSalary")
        self.gridLayout_3.addWidget(self.CSalary, 3, 1, 1, 1)
        self.C_antikeim = QtWidgets.QLabel(self.APPLIC)
        self.C_antikeim.setObjectName("C_antikeim")
        self.gridLayout_3.addWidget(self.C_antikeim, 4, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem2, 6, 0, 1, 3)
        self.C_state = QtWidgets.QLabel(self.APPLIC)
        self.C_state.setStatusTip("")
        self.C_state.setText("<html><head/><body><p><br/></p></body></html>")
        self.C_state.setObjectName("C_state")
        self.gridLayout_3.addWidget(self.C_state, 5, 0, 1, 3)
        self.DeleteApp = QtWidgets.QPushButton(self.APPLIC)
        self.DeleteApp.setObjectName("DeleteApp")
        self.gridLayout_3.addWidget(self.DeleteApp, 7, 0, 1, 1)
        self.CAntikeim = QtWidgets.QListWidget(self.APPLIC)
        self.CAntikeim.setObjectName("CAntikeim")
        self.gridLayout_3.addWidget(self.CAntikeim, 4, 3, 4, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 7, 1, 1, 2)
        self.CIDPos = QtWidgets.QComboBox(self.APPLIC)
        self.CIDPos.setObjectName("CIDPos")
        self.gridLayout_3.addWidget(self.CIDPos, 0, 2, 1, 2)
        self.Tabs.addTab(self.APPLIC, "")
        self.PROJECT = QtWidgets.QWidget()
        self.PROJECT.setObjectName("PROJECT")
        self.Tabs.addTab(self.PROJECT, "")
        self.EDUCATION = QtWidgets.QWidget()
        self.EDUCATION.setObjectName("EDUCATION")
        self.Tabs.addTab(self.EDUCATION, "")
        self.gridLayout.addWidget(self.Tabs, 0, 0, 1, 4)
        CandidateWindow.setCentralWidget(self.centralwidget)
        self._username.setBuddy(self.Username)
        self._password.setBuddy(self.Password)
        self._name.setBuddy(self.Name)
        self._surname.setBuddy(self.Surname)
        self._regdate.setBuddy(self.Regdate)
        self._email.setBuddy(self.Email)
        self.C_idpos.setBuddy(self.CIDPos)
        self.C_recruiter.setBuddy(self.CRecruiter)
        self.C_position.setBuddy(self.CTitle)
        self.C_edra.setBuddy(self.CEdra)
        self.C_subdate.setBuddy(self.CSubdate)
        self.C_salary.setBuddy(self.CSalary)
        self.C_startdate.setBuddy(self.CStartdate)
        self.C_antikeim.setBuddy(self.CAntikeim)

        self.retranslateUi(CandidateWindow)
        self.Tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(CandidateWindow)
        CandidateWindow.setTabOrder(self.Tabs, self.Username)
        CandidateWindow.setTabOrder(self.Username, self.Password)
        CandidateWindow.setTabOrder(self.Password, self.Name)
        CandidateWindow.setTabOrder(self.Name, self.Surname)
        CandidateWindow.setTabOrder(self.Surname, self.Regdate)
        CandidateWindow.setTabOrder(self.Regdate, self.Email)
        CandidateWindow.setTabOrder(self.Email, self.Recommendations)
        CandidateWindow.setTabOrder(self.Recommendations, self.Certificates)
        CandidateWindow.setTabOrder(self.Certificates, self.CBiography)
        CandidateWindow.setTabOrder(self.CBiography, self.CIDPos)
        CandidateWindow.setTabOrder(self.CIDPos, self.CTitle)
        CandidateWindow.setTabOrder(self.CTitle, self.CRecruiter)
        CandidateWindow.setTabOrder(self.CRecruiter, self.CEdra)
        CandidateWindow.setTabOrder(self.CEdra, self.CStartdate)
        CandidateWindow.setTabOrder(self.CStartdate, self.CSalary)
        CandidateWindow.setTabOrder(self.CSalary, self.CSubdate)
        CandidateWindow.setTabOrder(self.CSubdate, self.CAppFile)
        CandidateWindow.setTabOrder(self.CAppFile, self.CAntikeim)
        CandidateWindow.setTabOrder(self.CAntikeim, self.Reset)
        CandidateWindow.setTabOrder(self.Reset, self.Save)
        CandidateWindow.setTabOrder(self.Save, self.Exit)
        CandidateWindow.setTabOrder(self.Exit, self.DeleteApp)

    def retranslateUi(self, CandidateWindow):
        _translate = QtCore.QCoreApplication.translate
        CandidateWindow.setWindowTitle(_translate("CandidateWindow", "MainWindow"))
        self.Exit.setText(_translate("CandidateWindow", "Log out"))
        self.Reset.setText(_translate("CandidateWindow", "Reset"))
        self.Save.setText(_translate("CandidateWindow", "Save"))
        self._username.setText(_translate("CandidateWindow", "Username"))
        self._password.setText(_translate("CandidateWindow", "Password"))
        self._name.setText(_translate("CandidateWindow", "Name"))
        self._surname.setText(_translate("CandidateWindow", "Surname"))
        self._regdate.setText(_translate("CandidateWindow", "Register date"))
        self._email.setText(_translate("CandidateWindow", "E-Mail"))
        self._recommendations.setText(_translate("CandidateWindow", "Recommendations"))
        self._certificates.setText(_translate("CandidateWindow", "Certificates"))
        self.C_biography.setText(_translate("CandidateWindow", "Biography"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.ACCOUNT), _translate("CandidateWindow", "My Account"))
        self.C_idpos.setText(_translate("CandidateWindow", "Choose job to apply:"))
        self.C_recruiter.setText(_translate("CandidateWindow", "Recruiter"))
        self.C_position.setText(_translate("CandidateWindow", "Title"))
        self.C_edra.setText(_translate("CandidateWindow", "Headquarters"))
        self.C_subdate.setText(_translate("CandidateWindow", "Expiration of applications date"))
        self.C_salary.setText(_translate("CandidateWindow", "Salary"))
        self.C_startdate.setText(_translate("CandidateWindow", "Starting Date"))
        self.C_appfile.setText(_translate("CandidateWindow", "Application File"))
        self.C_antikeim.setText(_translate("CandidateWindow", "Subjects"))
        self.DeleteApp.setText(_translate("CandidateWindow", "Delete"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.APPLIC), _translate("CandidateWindow", "Applications"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.PROJECT), _translate("CandidateWindow", "Projects"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.EDUCATION), _translate("CandidateWindow", "Education"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CandidateWindow = QtWidgets.QMainWindow()
    ui = Ui_CandidateWindow()
    ui.setupUi(CandidateWindow)
    CandidateWindow.show()
    sys.exit(app.exec_())

